# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-o~^UuYCZ7@yhQ+uQ73?h-GiF^zFe0?oz7SWO=cRvI;8OFaWot5@OJ+>Y_$-tI9wXYN9zLHeL5HDbVk3M~qaM6l48Li<qhp?$n-"
    "VlR#-6nye6G%v-"
    "c&g}Kh=%pZZVdu|&J2SuU`+eVUo`W@yRPNwvmbEv42~22#6pTU0$ATrq1g{rkBI`v<O8H_wW|LyF>5KVI&6K~AVhZd1tgkZzrowv"
    "FtT*deuc3gcp6vzz*9!pgS6le^;00LjFTk7-3BKUN2&9@}+YT{E(y`qrn@ht6IYX5bPRd9mi8I-1CS7u>GOZ4_qby3Sb<4+Ik-"
    "N3zxkX^bK!nQ3gr=|{mdE%5;;a2*Tn05y1@?H|I=0F>wbnKQ)|?Rd|GP!RD3woRXA;>5BYx^1Lo8|pQ_;=2n3GCX9+M0)MlD4B7`"
    "cvh4pBL6U}O`j#N(%v7K+F3fmOaC)hr`pC(a<eJ)NV0G<L>Og2b`o5ZuV@9I-pZnrTq-"
    "2d}s@hvv|dzpE4q&+fkwy%t>zbrwV03ZZR_q26MszYyxrEBz%cG^<?RThz7|w5^L;XHn}ZXgztU2Zz{Bukj^R`09FtuZ0>`CN<B0"
    "7>x)XG#VZ`Iv71L_}P)@P<-gbP&_(#cnAkMtNa+;;Qiwg!!`}eu~D4GC7xz!g`1dV19z;U?3nh><-"
    "JR7eFd#AFZGo%3TrUR6^yq$jCDMNfCbJAQ^L4V%h9;B&NqMUHxo?3DOO?&l~M#b&<TiAv3CI+hJa|5`4qUx3ULbF1h>UX{y=b&t("
    "pK?@g$gl5h;o}pcfyr<|R}kGL;h~mqsp?Cz7^lSyaxr2=CfSwZq7DjWM*($$n1jhO!Bi=CwzCX`Hl4M5I2FBrJiXQOC^T79K2KGP"
    "<sp<LXb9*JGW{nz{K?FP1BU&)4x(+4!dtyjp*$zNoYnl(wSMT~NB`o94;)$9_EUSQ-"
    "4gq&58ops%B()X!|3@z3D7uDRxXQ2#^Ox+1dgFI~>Uh4=fwgH3~)_)vwceJydSq-5dxiF2OOw5FujA>|x6&j?tLn#vw-"
    "^AvQ$q*|n;T9T%~>9{Q{2vzbJHFzJXubvpJ-Ip}JBC|rF3CD!B-"
    "^VxnxA>USeP2boy!2~YS8!foXns2kWAJSe+?UsQ?2jnXNv*fnMb_zFf?Sf>&J0mUM|Q%o34U}>w+!7#Tge1d>qkG>I!i*7Mz)z`T"
    "7=kd1L_OD@xh2d#l(b3eN2fGXCn}I@(SiBMFL*AV$K1T3_Ny@$|%b&1J_GEstgVfdzDXBH#5rgE5Q<zia294NhBBtJW0feWH19|B"
    "I+A<7y_2zBGUs}$Favbb}BQi%vj|0JeN{N(#AX3a0}0eugij=ZeCQkOz&TA*nBtqUCXyE`G&~!C(By!>cFLeD|?=VT1tWN?4i7VB"
    "tJazTPELrY$<SjIn?mP-%x6N_eT4*_PgP4M((uCf0WmE|Lp#<>(_yY13!J4KmNs1<Ee}Ca%f{Qq!&VZUeQZZuqZVZq^8-"
    "#T<7&OGqJlP^Wg`r_ge47A4?xDYXMKLxU6%a@i+^lTz1yG3?eda=h5ro&6etDr{`Lfi6YZdZzA%l4^ov~4;i+aT@aYZ0e4qp@8{B"
    "KB}ct|@q4@p^M)r*nIg`I7b*_NHd1U8s*dDbf>J}-BzZ%cUn+Z2j+wF0UcB2&Cl=l)Ygqk5_zZMB2aQjG`V6$J$RN-"
    ">tt>b9=RtT?7U8zl0E9bM6&ZG{ZqQ);N*j;@7bkxgH$73Ct{uI8d{J%7OKmG6kXpU-{sCDX+pq"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
