# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-l=;J#Q2-5VdzV3G4y|Ae0IX<rcT;s1O|mQW9~ZLD%?<*Ey_sZO8T|IuxW7DX3_nMWUh3Pq;q-"
    "?MW0sMHh5kD#n{g#FF0|jpy^pzsa>juV{52@gr%;gtT-"
    "<C$!B@$t0WSb<zLAr{^Y0zsKLgIKsGBVjo%wuWZMKinb}sZ4QDv4u>lATq7MykOsy(+b{>sK`+i`O7N7$okmNj#hC#oeaDRyL-"
    "31vd}B=m@JyGEAM`RxFcwtjtdBf(#>#^G8TUbg<DLTsVf6sc_wqGzD>ZaBT8~`^v$f@PIvNG3_eN2MIGsXJGj0&2X)XB0XQx^lns"
    "QnC-mrtnxO3vVL~D4fB+<i5iBK9%I{J=Ml96ND=87DXFZ2U_N$O(vPg1m|K12FS>TFqIy|i#t)(l?st?wV<8ev(n|2;!`1Gu;wyx"
    "8j17Guh&$XMg%L)rj12MPBOPRNhq@z3hP_X<8G_*TFw4ZB<C%MHd_D;P@#*P5}*{IrKJ6Wm0&xbXzl>9u_7Z(sd`u!(S<Q%e74Yq"
    "U7OLvC%pZ%#H=>p6WiWc~w-Eu8f"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
