# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-n<lO>7&-6`tAurAU#YDN3?zgR-T{n-"
    "r2<$u&|WX;nE0oZ4y}r7^NiyjXKb%F;`&GP{f=VTBr~fRcb!$p{Lmr{*ZbmjDHdpr^V%#77e{Aa>&d3UVlVqobrQbn475Nz)eXa-"
    "la*^WMC9?|t9Q?l++2$A<&ldyB{oU;qPJAP-dtsm@r8$^;{;vSef}F3+ocUQmU+sEQCU;7wp~E5P6pf13?ssnQ~&2>+(40{srXP_"
    "SLyHSK~kt+2j$@t0R}DC_#dj5$}(EuWjQY&YAQlhnxR_eB1VWQBkV4L~x1D$4-"
    "GAwGNzhU_ZTcNGk=1ZJVZuE?q=1Ns<JIJSEXndHr@5{W0%ShtxljuA2V74CLD6*XcAD?sfifd!~WXMob-"
    "N6(tNWzYQ_+gA}To+nOk7g51QnS!0UV%Z-Tkxu`c*Rh_tc;S3zv31tD`)A7zZOF=8voVR0acs-"
    "Xnl5!1@uL^t)3HhP^QPlwnU=P&;UC;Hi1G)x0o<mk%y?jxK<UBTu--i2@(pWF00(}J0zIH{jX9J4*Icy-Zoz3q@Oh^=kFYOknprS"
    "iP4i{<BaC#zEX?`bc{_X6=QWECk~WVDbef>dImnvz1yU$!jW26j*3unE(;QkvCUbqi$HCdrqB&{=&D5?0-5i-"
    ";#4+Nq)ZN<Sk;cxQ#N-"
    "SS@!#v<p%g2N6{&YK{Xoh*>^`<}`R3*A?x7NQBT}85Dsii^Jz7Loe1=y+1Mfk~br&`p#5})2IqslsS#+CmbJFwIE=vaVcoQzm9>_"
    "%w`kf{)d6Fm368Lh_gLY4Rl`=AT8vG<HK(6zkZ?3D|dJlSx$9miXbQlQcfY&@Pbm!cmHfw|@6na6{ZS&1_x67e5_XD-"
    "a2J9o+3^)N!0S8_qS-wx^A-Lf#u<wIw@Y(q%D?<A%X4>aJ(XApPXOk-yO~dD@obcI?&;q8N^7%JDAvDAZqGQ@7U&e@>NXJEn&!N2"
    "O`rI|0NOs<yS0Xq`UAU`efrN5R*FwISM~<V<5yhSlZZcmq(5zmxTwip}JhF?fAF0RGXa<OG=t~$m^TZoDk%0D%AEtfsS>3t1lz58"
    "iWQIcGd`ZN0@Ldw54{xY9)lWaz=^m;Oc1Ip2`ZnS><J*aW5?>vBdF#^s6Q@g3HP*GJmeof9%0H<pBcDt6Prgz*yLO>`Ve_R*bm%c"
    "l=69v&T4%X)N9wOg{hM!Xaa-u~OJB_WHGeO8@6rS5S5+yt7AZ&8&peR&TjGsXqX`;lCwjCJJ-"
    "V6O8hj8Pr2)rw<2{>VC7!u2Wgf@K1~t0-{$uHB)4tP7YPrKErzH08$Bs^=*t-"
    "%x)g|6d@lyk0mTh5*&^Vrd30_5nV&J*tYja?8d>isL@55#GS?c|Ub>JfK*bm6eGPlf=gTfn-"
    "9ypK7iO)aOklc(1$T}R75z}H7u7zpr93s4OkgEs*ukcAKD1m*keqCaPPQ65N7n(E)DI$ghGL}+L(WE{*OqaYHP-XWCViQ$Dn*7cD"
    "PI|bK9^Q&<r^icgQp6^{j;E{9WcBbsIbPyR3)Le7C275<BK1-"
    "1<+8lmL4lm0Ku+vC9VGDTk;yoFC(cjyidonWs=xgosN5#NUfY}WMU8Gk2M<68&w>w0g97N7W!7VI@{0hw(ZjU^ZLkg+tyJLy(0tA"
    "!uiX$jA-Gi>JQ89Wpf^f|5?mo#^Kf%@)I!YUtYte$(=BT${S<1=`BN0PcLLm6PTKgx^x@5kKfU(H*LM0xEB&L}{in9mKMJ86-"
    "^~nvOMH4O(Icfd)?cYcyVlN?&#nIA5i#~Y=7|SIZM=@!;AD!ulj0|jieYW+v=640PJBFIB&iRdpmm&~Vz8;vH|tV@*8gkb@?plyO"
    "xp#7f6#QGd|QgnTDI=ijlO`9Tf~LHPI`2*>D$-"
    "Plo<VVDCl`aJ{=;OmbZ<fMfIqreO%P7x<%A9!_I0N=9?joQ9(Zk@XJ(C&fzgCPSY}C^>2zSvMfzgAWqS)Qp)@+zyV7QL8;+<N<SM"
    "`z(2V6zD}gqoz1Dw4t<v0di{&>?Zi*7pZlI;`LnQ=0z*o*r>~kBti_Z3z;0((jVEJG0Et62k!li1cGqO8ML_a+t%GV&Iv1l_CrBO"
    "(R@M?A65Hz{+M|;|h?Gv0oZnvlmJ#{X9t(t2jcWf%a(pjNH?mY@+MU@VX(#CirspPjdEvvf+RnEZXG{bAc;uoxWn+XX<-"
    "%48jR3bm7>pLbFTEP}`E@)QoB+~+3=uUJLikT`{2P$?3UvGnj8(wccft>0@A{eV0U3e_{{vHhj*<"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
