# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-pmCU2qe}9pAk#oh(^0mXJSii~t3YZA_Cuf$-"
    "51LsM#SVw<EL0a1^;!<DSB?41KvWXgkQYPV!;nq({wOz}e>>>)Go2s51~%~PK`7BaPSLudLqo%D&|wA19NyL&oGwq(bdwwlr2-"
    "tPbQcK^TM{{H{HzksqIZ(iVX4=$&G0u&enaTtP-"
    ")R`C)XG1KlvoS8thxoV<65_UyEiQ({xIJWtfB`Q9g&PG5ukv?TbG%T^un@F;N~%F<IHW`(sY`k!nb7d9sHkd6PNs%~yiwnK{Gz5K"
    "N!CwCH2q9cQDcUqmtIdL6!nV1^y-"
    "Gt9~nqUF@x)mC3U%c`kXcWKjZQzcmXO1K?Q^u1%_A#sN9``VTe~YDfMIE5>%Mc+K_<zY*rs`V@F{~RP9kOsQBSt4);0~eiVe9ibo"
    "Mfxlpa*Rc!d`QZ_3hzPc5kV#n7yr3PDVQW_KozN=Rn6(_!W@Y}rVW~KH6*B!<j72CT<OSAKt7Puc4`s+qPvA1CiT!Ep+eh_Rj+^<"
    "}Ws%73vAETF~Us3%^M3%9SB@{_&emR-&qhw6g{Hmr)7jdP-FQrg26_J#rKP4f_-+ShCr_7eERlt9ixbt_o@;;mbda-"
    "Mq&wzI@TQZC_MF@1>>dio_H3P!M5p{cI{|PX`PH-|C0Wx!;1%UI|AtUSvr`K4vQD-Fx88%Iv0!f+S-"
    "es=0azMsUjj;HAHp^;&yj`^JhVdI<!Rj&yGCiM?DFp2XuMMSCWQgH#BoWcWVT0F)QZdyK!qi`eT}=$dRV3*uB10SEYnqDsaF=1H7"
    "U77ZVdIFd#<ieeaGDysWbo#*0(PvL&<#F9*~=mGv9KJIG%Xy~h=={;ckN5BhUC3Nk-aetWjIbi>`V<KH#SH&t^&E!nrbcX)xM95e"
    "_sQS#oBROPHfEj7DWGJ-<IsjcVlDRb;slGv-"
    "7Wo^4;eao6bMzzJKzgeYdvXZl7+S<#Ww@?!jF1bNBY;nh)fg&SPuW()Pd@_m1O>WfnAFfEq#c?zZFG1eqywKWp*gRjLvh7=@J>S#"
    "(8s^YsJ0$bt-ra#gGgBlLqgrU#Li1zE!u(O#Eg5yfC*Y65L0jSTXUF&oLk8R|ULLP0^v%U#K#gkI?^tH(p0*@}y6V9DD&)pMg~!5"
    "bKRb6$M$gB`QV-NCuReA|ooZkfzu#XjJy_4?oj*4wE-"
    "Y{9N=Av0H)!Dh0GvK<4W!rERL#7ouKVZ6tNiKSR+8Ff_ICB?mo_XUeOs=s6Xxi+meHd{hW!GF|B&=C;vufbxMBR}y4!3=q6+kmPE"
    "ITJlHC~BsygX*xx6*hs1B&SHal=iMhk+hPBwYZ6(+dDBbK63rXGt%t-yNBiu-"
    "8sCl^VF|A_s@QK?!meIp;Hfco?7xWJYm7E??GHya@9{H#uJM!f6nEf@#bAS$JkHy9T?Lm-X4EDyZ`o~=|eXU=iIv%-"
    "R(Jd`)pU<{f&9?`2DlEK-"
    "&ps<%o+GAI41ngD9wi$U0udss|^Sg6cICR1c0Y8JJ<BeC2aWQ7^I9HBqf&M)0mGC>pL)MN9KT`lUSwgRJRto=TD-"
    "s0kUn5V!h@e&-TWT-8|9@uuJHM4Ng@bGoT=3l+MErMBNh;OOxW-"
    "+1uG;?dsR(cb*g{zdoMx%8}l@9ZQusZ0&t7@XOa_qFBf+VXDf#j{`F3q|@DEyq@>NioX&+VbW)y9;8zV(&3BGeCTY1#pBZ)0QIRZ"
    "!p*0*iQ`hDF`!VyUe!k*c;wkrDqCp1;6Psn1eky0=O@#1Cd0Zs;Q>?5NB-"
    "#qgG8Qr4GX>6JhH5k(3xv6@ydb5#53*NMWJ~u7Jsg)KpB8)pSDzNM;Awf!fO^M51$1Y{`i&3u5ci^9O$KJ2)G7@5&7K{?&)RgCsU"
    "kgXWyrydbvFdQ(npS`=GzV(TN(|HV@tG#sKa;QjjJ&D;vqcndW^HBpCUK4#WdGJ;1nhU>P~p3N{AO|}e~Dx*g2RYr1DW*Ma%1&>q"
    "v6%24ydC#Wx8Gt%zDpAtB0tZedaH^p9B`<4;u-p)&R0=bI5`uD}%-"
    "}il?DI76nGAS=6aj)}IRVfCk`ee;gKrM}EV2Fp#s0Bt(_~<({YHD<)jGx&nQ-ge%?q<#_dE;Ye%v<U7<ZTixOH&m#LZ(1V%z$ZFt"
    "xC1j`%~$0}}hn;@bvUu`0eX)uI%QMC&rAwEI`!ZLc;OR#c`K8$q<D3g)%z>NhvR%PiF(XF<QY5kA9bn74oiuRAgvRv;G#Mg-cvVO"
    "C{uq|OK>-WRi0euTSRh_dB86NXX>$xOLoT=f>!!$D$ZL0n8`*-"
    "T~ysF0XXY6crouF$A}+DXwsIApW(QcHFmrZvrS(_2=vudK6!JU&&3(RGtu3+}dCJF?2{!Rf(#bK66A+mf>$N9DS9d@V3=vJ0oJi{"
    "jRtxb>IfY(w7v+=BQ#3E0u`Xx5XJ@-9DS@a~Sgt~uA@?jyO~NAkOmE!Oo-"
    "w`Bt}+(&`m?)rG|&%N_?ePevCu8)$ok&gIGPJAXS&%7|pKN34hO1r5aYUDWan}g1m+JujJ4wuzc?H}NO#^#Nw9e&eSsa*yhU4zdn"
    "^y_PKnd(=o$&S_f)u+ajZ>c5yGQ(G~tteS@Oo>=4(sBV&>q@;c+xHQBX~SfxlrU%AME7`imYsLDY(%(VwL{F#b<&Q3GAXfS9wIXB"
    "IY^hRk?z7`c{!#^D7|_0T50nUV(hZQ@`Q8TIobC}Y&7S^R6A_E^<PpDZAma>)+-JfYf5V=oww+~mZk7iUS3*-"
    "E{#x?nL1H{ZxPdd=4u_zNp``p^F28mAm`4!ZzsO{qucX23%o7a6SupkyJy*4OGn<bXWqGI$?aJOs}AsWl8ycXVoWImLnl{)MwPM>"
    "GMaatAf}tlXzFgra<?7Rj=VcCF9zrg4M*?m5{gI({fv|fLc(=zD5h6GDR-"
    "<xvQnOM1!@?wNO9uOOadw#PvU&qvwG6_ghlc`Z8M!R_VC2;_;A+qv#Sr?J7((V#U1|#$NJZDEZz<DI9|CMNOO0|wSRTjPwtyKeB*"
    "H5y>(vPO6O>ePGV8oPQHko({ywJw-C6#tf4JRMAk{u3+Aa2-{JEm4Q*^Bq0<eAUNOfZt%!WAC|J-"
    "s0Zbo4iL`?}>(BUmk_i<X_Ywp0{WI7^J_?bOQaEhXgvm#lp%|$<!{IlFq*$TH77i;(IUGjh=wNCh`D#NI6Kx{}{cPko5z%mhK1{w"
    "Gp<Sez_?&79&FRoFQgo5xJH_;mEEn0W8B^TR8LGsEZ%DEli-"
    "p6OC|fM|f7_&p!z#$Ew4ai1M5Evn?z?~TG`)N9+Ub9B9RKWRPO!D@W*n#R{NX18@Nd6;b^7Wu;P{u|QzztKgUbTPZ(DZqxNr&l-"
    "sL)h-"
    "}bZ)@=ePE%X^n=ARa>iLe1EY$@l^vc*;ONfWxft>=RO>U6Y;#e)DJe)=xTopOc!2F_~OX&_O(VX$S*>eTi6#CHWX^=E$yBhx;Rn`"
    "pwQ>y(@`S#1|b)d}?~!ZVfgE%z?@JzZ8#{a2-SEsd{545UxI9A%uSb+y4fd{tiw*0;fM0PD1FP_wD{CAQd{oe*m03hqV"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
