# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-"
    "pO4TW=f36`s9vmt2~<Te4kiWy=@FE@dmOlO~Q4N0wqGu@YBK3Nvuo)$U5Byxdi0m(>MwtF{6{HcsTC2&{)ZI2WKY+!iVN(C5^Dz^"
    "rAETG&8<6e#*e*K(UWFFmu%rKnpWAYDQ;vu9?{%$)ho`OfGoRP%6tMLqfe%Iio&8fBmim82-"
    "rrVTntL(LdWhE1}bj5W9npX9wZXM{3BQpku&F%wRPGm&H@BPAsY(dcEQ@v}$^>B23>pCcLdqyk7qU93vCdD1XQBQ;}VlXP7A2WiG"
    "BH=>xP<tR?tGVK9)7kU)KP=*X0+RQ0)GS0c7bFUAL>Z;?4=YEhiP15N`&Yi!6bwzu_vJ96WOplm~;j)8<<*2nLU;`7J@JyhiB&DG"
    "wO(UJr*;`a)L7ex_>-"
    ";UcA_)=6t%{PQFiFK}H~K>hU)Hfd7pzrug;dH^GI}cIhEu7GrDYA$mQtyAvWnsNU=b9!yyb6z$GV+09G9^j>~cEB7IuZ<w3)Uq>D"
    "o>7h|Kn+-o|QIHr+MuO=l;@Cb0x^uL#4Ry&H;Iv=nW;*7x3zX8M+-"
    "hHFpHGk2w3Grdc(=JzIkeg?M$AFQ$l6IkOUl<(HqL!*+6#^%s4rO~rel7-"
    "!K!R|F?7F8|5=g<U|3=JYU7T&i<wih~jVS8CeksYiIDWjG=WLWQHb;Wda*-"
    "o3XW2p+3i4h#jmPhdIkB8GLv^3q;bXhm#OKHPOsPvk(#>iT)LgPc~I&!LAd3GAT58w_~MWJbG8l|dVPt)+mRNokQV}my*610M^p_"
    "i|YMWZpa?$M|KDHNJSaeCl<TyQx%JEmg-"
    "0XRMfj$Ihenks>@%PM%pcKOTWr1nn14cR_w+^DTPr?QT9S~qk@2P?9+ZVcn^kn<wvirdL>F_lsc#kNx^n>euy&kWv9x_3b_74t2h"
    "2<C1isCW*FuV>JGA({^rgw{o2N2yiLu~(y|rdFuLQp+x=BKNm<{^n=UkV=A76m}GZ9rMTT39^S6m8#h_?;is7=x-"
    "Ep9TEH<%(LD)L`tuhriq+gFaM1CfVu+5HOjB=8x=N?MK+kR=0G;l)Uq{AD-fDQdyyjr@=k<by+UuId)wA@JM}Ao4A$#3R=;T4d^J"
    "HBqR<71#8>E_(pMe79;e391akq6Q+xk!I}bG8qz2;B8YE(w6l5bVt7p;>f_o=aeT={ylda$e53b<$sy?Ksm)-"
    "ENg)@qi(kE0*b{J>yo~jB4q&DLN+Jm#p;H)_nuD}`EI|-"
    "7>(q>SZ4T<qm^PX$xuV4K2#T%!8+y8O@o#q!lZ~F7jKkh6vzmV%I3n*GY_gen7qSRiH+KW<WLF&Bm)}nOyOR3J6cNC<KqO`vt?Y}"
    "1-{CYWp>e~K^D6x+!1tWGBq}@enZ$aAoS<eFV>6zc9i;0&CiI?ssP8X%#g4Fv>nIRv1Qw~>WTc!1h-"
    "39CY#r{*>XklNEh`#6+dwAxH=TA{R6!Vu89EfgH9Efi73~7t|d%Bo7?HT$>L%?=#ClZOnGVtBSxPYU?VgzM4<^_*bO0!hp65{-"
    "rPyjwe<k3o$P<6vdrEXGqFR>m$+KYa$XbXxu($PTz1n>s?`eT;oIv&;`KK#qK9?}9Af5aeOS|%-"
    "@Ioj4TN0mp<Z^RrSP4KvbnT;k{jrM-*M~sNp{xnhJX89zig|!Hz5L^wPNUm^Ru`d%o&-"
    "TD1eTsTX(G*#=GGhvM($Iujk@cUX9pDlb$REpD(_;>K%mN7+od(7MEUM|-e=-vTDzk=Aym<D9^@PIsgi;$<9Iom;{N~<MOD)qh-"
    "Z{PX7)IC372QB@D3DDeypMR2fOiHAfXO88wh_Y`QjC7nb`(?9U3QElL-oKgXO#&*J?gQtCP_DR2bijoP{di!C0!ousY7ohqfDe6Z"
    "@BG4i1l5xmU8NY!>N+aQ)J}H)uc1uvM9*+o7#&_i9%E2ZqpG$JWG)l;%)u;{-"
    "SiCARSnUEK0}j?>qSEn>qIVs0X+><BFD<s$@q3H2vHt0<9oDs%8gFCAIakgGGwq@m&FqlUkvN5o((Ig!(-"
    "XB*YWK`IV60kfcVr^|HKBLoPJlmlwVjRn;8xG_$ETX^YyJ8g1;R+O|kg)9i}29Lfp9;LWqbmC(1;8d}i`R<GOOtH%Fr^}H}hvaEH"
    "fYh#eee@I^^syE0*Mwty%uS(y1U!w6dUS!qMHe{w6y!$RuaS;NQ86W;`2t%r-*!q-"
    "Qbpbm&1YDRnVL)1I*e4T}5hQHc&Avwv#GlQd^||5(@Pr>(<6%E2d$Ti&rqvK^NVQB8ZV5iI67s~yh@1oW#!g)HiPYm~lI!8;NpWH"
    "|U7sSwi)0<--tlAEe|$P{d4Jtgu{9exO2&T<#eZhdasz5;ofq!Zci%Yn*ZS^-"
    "<AwU}91pqTTr?jo3T*|UZGQiv(6JP0DoG7<1Nnh~4&wzWz7Pl3UWznUyX1l-7o~#*>EJ@^qSWn$f=U;m+@f@-ARStGby0fuF-wV0"
    "m3bt_=C<Xx6@~VK&|VY{6odl{p+(^cS%H`r=VJNTJijQkmtxI1KX$CUHF!b(S?|6#y=9QBg#N)QL_F(9#+9_wXW`S9sRu9#JL!yW"
    "Wt~*U_Mj4EGf^@&1sM?VwW&|FRPDS<{t7Yob}z>%#Tw@(^OMC`XCc;kBY8J=<c@H}2MRqf0MmV+#NIHlnmjEJkQIb|02~fbFtw|i"
    "LA*_}hr`~mi<RLXMy5JehQPh^unfi8aRf$FZ7bu}^plILlf|Y7-Z+)c0YrgD&Uh$>)!|pX3~>ndx-Nae-"
    ">tG1xhdj)QY1*xwI*FT8Waae$D2XAa`s;=#~muSpr@ZH9e=KL^m`AZ+qsr68#>Dz)Q|)=9Vv^X6-"
    "JH6$`R6%P)k>tj4IcmaNVPNX#KmJ;*ORP6n=_B=84yli~DdEwnnb%1Qz%p*-"
    "1>b3`6&Bb9O=*QZeiKk25)zHb*e$k?$LmgK14ao;c_9SXjp-"
    "V&YK1&EB=&Pt~MqCg$yr#0P%`WY1586aN1VPU3T3fP#&aGlQIyq8^|<U!l4OsPh48`8zsu51m=&8LIW#%gYF=WvPjZ=PoQGsFo9*"
    ")Y07dV+56_{J%2)pKb"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
