# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-"
    "o~{drVu`8NV;v*KZpzU?9|B0+<9so1_pz$asW2NJtgP%USB)_*~rU`a#dVq``7Dv}RJWrV3TJ#o5x;NSOjkrZ9EVvOlJ!%A|JHCf"
    "Qsh+$$<o>LxA!k&<m)wm){xH8!RsO|?1UyWhFzJKs6q<9@&I-"
    "Y<xPpDueLmw%4vRRR!z3=v_{OOlwULX?+6S2{$8884&WV?vs+)~iLl253XNFzaOzuLCU50|PJu6EI)bdiB5ptiT5Bpa>MJcMKH4G"
    "oS>N+;-fevb$2mUILU}AV68}&aIVWd5xd~lwV-HCQu2S=xQFPJXH_yl!sJ|TqF{eI7x^`#6dLH15V=nAx;$0fO(0NUVT7jCH1}C!"
    "@l0bM+b*vI(K(_Pis#vVqV<d*SF(&#B6Wv>F@7HOi$~Jy(-h+-`BQ%kIHQC-"
    "_z#NLM_tt03YuGjR}K^1`~Cn6_YAVte9YT2LAjf{QJ-Dz)!E?-ye4mdniRa0;4fLqG-fWR1*D#F`#oXh^R5(2`>o<FLe~ff~Nu1i"
    "SDW#t#S<FG%BY>oG#C?DyR1{s;ogB8NC{HWWpm}iy~saz~p_b8@G6Din*7Q`uGtcB4B?iv?xJ^5`e-"
    ")xG=BKLPS!ukb{CW4zbyaK?rjJ-ZzT8i~?~Mc^+m5gkp|DAs|G!kZ(i?@d_(STm*0sC{`|lR$=`<Q5p~NezL%PD(eDrxluJ=%1^|"
    "JAVsYEInmz`F+&a_r<#v+AK5>A5=Hpn;Uh!PnGHH4@}UtCZ{d3E5TSpIKMMIReopcQIRC3$%jmdb%39>}M?+B<t61ZLmcqH`kQUL"
    "7$OQ2hYgJ<S{ZrRYrLCS6>siK!!H3X7UK)cD=)k+P3hVP>&-r|c!RHG{!B`0MCZF&1F)p++WA*t8QrPE%8_-"
    "&HFNGb2(NP{EZ*N4y83NYhsX9zbas=-r_9F5F;&ayc=H86K{O10Q$@=C%##SOTB^kRzW*ix3<;0=Mtuj-YsoXemcydT)Hh!)#e@T"
    "&=re&JYS{`C9s~>A!6BJu6C>JzpP{`Gw+*;w!lW`J|F(b+|3e)qHo{;FAT##8Gx;O=BEE&|Tp99QoO-"
    "^%u2RcBUXC!M*CYQPAHIhBAla`9|^DF5Bi{f<9@q|6JfxJwF3=n<9BzgLWNT0SqpLV@Ik-"
    "Y4X%2p+ws9Tpi^*K_cP(@^O<DhfBblwtOoO-5a{nIq7UT43B219`c2l>D4qmS!gU0fH}oFzn8oDEh!-"
    "708{>%VCp`SW)uS2pB#HcHRsd6QK03~S85n8yopZKQJ7^M<%4=zc;5=A(qXzyvq0myjA(WuNI+OM%BsNFy6;e1g^AA`jw*I2+eLb"
    "3g0TBJ|9awy&+U=f<~-"
    "Zt2#ZlSEI&<+mB+A83&_<@GY4_yTdeB<JBFBLDO|)ci0?%?0snS><B|ap@yYpFy&wxDk}bO`z;&3@Cq3tqJGNaq}~BrutbC1J10@"
    "_b5=2;|eni7|~s0%z*gH7&=km$>L`GFW9<X|Lv+<+OK=)GQj>BBHV<;=FefsbEX_OLe~)x^-2P&WhaSA>ay?#aSm~BknRGh)s-"
    "VuRvsA78&2XlfSkN%!=R!?9S$#vF$==7W&}?NNHKuKOlZu7qJfs6h(`J`X{5QmSrh^Y3t2wmj{+eQP#7d6!czQr;(kTZs5p*vst~"
    "TWIS`*nMNx?JNipT{ydT54B@g057{g&T#yeeBV_AM-1tvI-tC+S1STH~oV_<nnMSFzt>pe~wpMw2C&C?TPgc>3sE*&#;feEai6Zw"
    "&72+WWQjXj{Y1uC9CW;;V%_zd8>Vzr?t2Yk3g$a%6e6!mi<v8yE~vk&KBwb}?w`|kv2g43t&x_{sJ+s1{Cfpo`!+;J$id2k{N*Lb"
    "hj`0<z?$4T%bh>v0KH!F1O3m~Rz9urzdBY_yJwyc7`c?_fNUgTOS>hg!~PoaBJ7sQE$`p<9lug95f$`~AZMT5-"
    "{6+PsUH4=YLQgnxh_COegis2X+8soFPet3Lzg{4tGp^i=zBDh!c^9ln5zogIsUQ+uR)UHZU7*%wFnC<E4Fn10SAp*<sG|d5kQfPF"
    "Pj{voaK+TuLhZU_Dg%S@G4dfyL9_n&7cr1zuH8??(xIP$-"
    "N(!S=%W5+FfPjt#xi{eRS#>;Wni)Y=iUTBo0v9;d5MvLk%e0ZP@EIN|4DLro3y$=fpBi?>_Vr-"
    "H@1omyN_>yP@m(}pCrz?(!$e=k;Y{p%$CqkoOFP;o2A3#WV_&osT?t+aCR(Pu(iJ-voPB9$-"
    "^Z_|oPDy>D_c%oq?cHt#y!!u=qP{pD7rK}KkNRrG~duUNnh2yqf2O$)V$4ouXdRz(-<x?i&kf%?gle&-"
    "Iy_zEZR#Zhp(P^=R^X$`|_N_lZ3LpX~Eu_wztam7cOcu4)+cJblsiCna0^RxoPKIQ}<mc*Y~6yJr@m`(z+Ys^tL<gGwrkc<W0NgH"
    "l4Uv@=^JR<sUc5-AB+Ub?k)Pa57zb@}lumt0PgG+;**cI<~N-JH4fQeoODiI~N9CP7l01Kky1V3bIvShHOaKulFX&8(Wjo&2v-"
    "dX4$(nazm%=-X&Lc$&TF@`<JwY-h73<#7>sZv*j7qbj5hdxM*@_ik*0M$@}Hk%9Hi7(=+Gnoc7-F&G=-;t_4SL+R-"
    "aJ_GHR7pyo7F)v#DyldQYhIMq1aCD(S$)qdyh8M(T9(dAC|-P|{|FV(zDuIrksJ9w{2b{%?TWzCj<&<4F>sS-Ky;R^(7TC_SQLE1"
    "GqZ#|r152I7rN+w^u^u1(d+PZmS-"
    "(pc&g1o*X`TDh8a*^jt!lbbvZ(7R|eaX^kI%%5To2uBBwr;z~WQ^7;otHY_?#h^KR|YN(EZR0?oHfb%>EdKns;nhbxoNt8cI$L!%"
    "GthHS)F)2S(7|FOHRdRxpaM7y0%TOY|lLB&baC_we>eWQ=Ug=oxSMqwBBr4(xF|KDhQKpV&JPs97&i<e&oI3Oc^(QNst<Q#$tPmU"
    "ZN5A??=^yz2bUD%36<R^ko@G>0AA1Mql<=#68WA8xNR?KWy4^po#j#Tza5^{-"
    "mD7w8?&8x8{>B645m!m&x_=BP%6WG_LmZfXt!V_sP}n9Z(mLTwlJpg4NCnb^WM^u#kkLS$!t}H0lkQ)!x9P863m!oF}4T&X3DlB<"
    "jLQ6p`Tl4_rd{{#1aE@S<y!gPbeGxzO{^`~AZG4<atWy8@gP6<gN9##U?tepUw%0%JQ)*JaQ1BnS!8PlpOXyw<386g6@3C*)NU;d"
    "wnnjFZ2l5zbOETOeDCQBe~ScQ%UN^0F1U9hWdlp;}sD2d)>CT4J(jqVL2eog0N+v1(LIQTc<oz!V@!ZvGX#6gM(|Bfgp-"
    "=Ga4%#mTKV+o#$W+}qObZL<5tRL4QteeiN|nmzO{5#zx3Yd4d>&}}B445fqL0Hyy2kis@hcBsu)9yQ@k{6etd$ri3)CH}f0R;gGy"
    ">;FygSHXMkj~YL0T<94}_YBEBM^oF6tso`DN#dau(~+@=B!pK`i9vpn;K8i3bt_d`(T_rYgols^g??9z1xJB6!*Pa)JJsDkH5M&e"
    "DpHjvWs5h(dKYaapR$J%x_R~xDpboF+OD10kIJ>lF=sq}olfjcdydVQA5SsI)x&uhcmx}3Kp5zXyYP1<h<nY)#UVkIPObT9a2g2%"
    "Y)}A`hTJ<f!aIY{H!>!TLG<1aam3(m_0;)KR=f!D1FGmSXoZ9`D_>avCxpg*7}~PvS*tc=M-Cr6=sUh=|K5GWL)q^E*jm+Wh}-"
    "YguLY>P$$ot3f?>5~MNWw#g6arKen!-"
    "OK^Q+HYCa>%|4P&#7qIq>&Q|#UA*x%{gn7wEl$0iFlSR|yw13v0wsuUI9%>27I9Znf^Q8Nql#y&&A`n@o394=h50|U9leR~rq>em"
    "6st5WnY4n-Y"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
