# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-"
    "oa#U2NOd6~6otN&Qi_q$IZE#!T#Hpi|pP)4Ex0BrBY`8Pd1~l%lQBfuMQmR1PINmsA=Xav`i4;BEoxzBDT8q1wx)!YLMDFTtKV<e"
    "_~OtrS)`7YHyESl+zFz_vW?UQ&N;+;o-U!*kF5JNLWaIrsb>bo>JThkCGv<#hl-"
    "8bAut29>4LG(~jAV6tqQ^>o$<WVtlw=>db!3TeU9IU|@3LOva$fzCqVMsS_-"
    "*QLRW0EVst7+$A+%X(wubQs297mQpDq$61ChEc3VgCGcCoJju<CZLGz;vy#}^W%70N;h;(%iR8RPJ+6vqiiOZv1}DL4C#VuXKYh~"
    "85L#lN0(kVv#N$oqxZ><GUbNVT+X!dFf(W2W)P~jsu`+98Z2(;<ok+hzcq7Tz%$O{CO3!7B|WEgg2psK8}~rdL7KwA(XV1CbOzFs"
    "*a{h}u`Mmo(m0|m^0MFxr`3$HIHlSylgZgGm&<2ob%Z$F?+OdK3(5j^#1%4{>1%vG<0&&T>k5jJQ?t6FxFJQ!nlNt=J)$U=@~YA3"
    "i786QaTVoL@PK&zaIb~5G0jB!7$goTc!S*N!XgUcPEUyV-"
    "`b1Cufe@Y?A^0<G5+q1FQVO7&!Iidfg05T3he_!Juo~_3g8N5B`ILH#>~^;kzbPy%T$4y4}5<=q?Yi8HrKQ-"
    "ah{D30?2g!BvwxAm-D)DS(oxTDR=uXSsj^@j;S$g=pH+cNva{8kQOENvYJ~`@i0@;REVi_`!jX)K5<iK5%Iwd*d|mL-Jorn2xfAs"
    ";RdH(IIm2-{OZhknRXe{8L<cxZ5=AOWs##v5+b0vT|TUuYAcN^J%G)m%Q}ih5!_4c-"
    "AEi>8~SAUqv4OAD!x>Y_HIT8o#<dK`ecQ2qVkP5oXGgCgHCv&%1(H2e+y~i;~+u$57>GZP#)UoNE_(_XvW_>^LWfZq^?sGz}T~oj"
    "`RC$zS*_~(7Fu>)*CA?(*+tuJNBlVdp~AA4VmVAG}WHl9x)%<#qa;)OuL<9nJF-hb25)PXWNU&kJ?duv=6eqt#uc{XUyA_9GJl|d"
    "+z7Ic;$su3Xx+@-zS`r1wY<-"
    "q+2E?ugfi{NXOZLzo6s5wUNtMi<TSGujpFd<1z{Txr`U?yg$~$`5>}@%y~>l1(~MpvYrgj=5r7a^cu1D3ZB7YJ;pXU8&ik_d89RZ"
    "(FnHo6Uvsc_y_n;5!~eyTd~CIOSRa+&6w=O<XY^=3X9XiZ$enSfAPJG8$$0^ymxJ|v{ZSf7C%}%dzX)IiSgBmnmDi_3~ce@HEZ=u"
    "Nx#DnZS@^kvp#v}qjze3qnmx>PTzQ~@5E-"
    "`DW~t$N~|tEu^~Kx<)%2~h(jB~&{jyicICIDn<2>wNwv_S&CswD8m=63LL)VH<i8fd@K;l@scuT^Ofo_<C5bdiNgX7mnpe9_+pQV"
    "9C7?Ea+d<X*o(8|X<kJhMqA;N~k;`m>g-"
    "n5l?8ht&{EqQ#festjuyGwWzG34Ff%)L~lg*;8JzwB{V8mHF+z!S<puiRQ$IU=OfnRTgg@&K}6et9~-"
    "DZIuZKKdg>n+P}0kHm^09qCb!jHnJg~xZ!@(7AQa5k=ew$5|mM?;u#IsEYJwzU+*sd|LGg4PmCRF^sWG+bgw@f(aK?pWeS@)^>^;"
    "YxBjt`#zx?FzUw$X?VJ{b+GH{R%EcEdL$#qMFg(hH?<e#6W@xk<5aIy}@&)0rAs7U_=B#6eH&7oN5@es&>&2!(bywrFNutye_``="
    "s9dYLau(CBCpGi0K@|&trk60oZjk6UXOkdT{A02?Z8B>Yw}-!3uqJ$+wMIj;e&zlgws8`!qpSKC0HJ>43?j&z-s?-"
    "Cvkj5*xeZKDV;ALt|ZF+mDj5KpLOETuJHA6;{8+ao%$-=U+($i!0!jXI{5TfVt;A6e5Uf&=g)m{@~<cFOr>t|wZ!a3WVZT-"
    ">MPq(;>wN)_VkweH+qlXNdBqk)1LLdTJo9Vxq7s(^tywe!>|)QUYxGS_LPQ7m&;nos0>wm#+=w#@l0JzmXf8pa;o%ZWnXpQF-"
    "JUBd~qwBSe-7NDbL+Z-kiIYy7}hk$?Dj&b9lO%N^hoAC#Bv=X<zcSFsibsnz`gF-Ww}ZxU%x@>0y}Ef>J@6F>^R2Bi+uU93o7VY4"
    "0{4c3U>W{iIZE43p`Z8JY9%`uWy{pCIC=&3Z|WxxAu4Q}gS#xjbGMCvrrd7dPB0Ms*9ZUJ*#Vurs)l@v0J@6n{o$*5ej>l8F7yl|"
    "5Q|H1z0zl0<lQ8X?U?VbZS=PokfZx|NUxXD+bKP!x3+Onw6neFF}D4SK%@J%0nCZ4N}mV(_0Fpu?*}cc^{;rdcY!4X}8?0J>+JG<"
    "QUXn%s#*sL^c+{NzY|-~R1D7iCfP_~14}lzYLXZ^6rP;to$#&!ztXm&Mdd"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
