# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-n<iPiqrF6rb7MG@G_TEwt8xID(g0Ou=&zMO!IK5Q_(U8HU-"
    "3E=+dUnO$s34m}iX4<4oc3Z?YqN9ZRI6l(D17f>3p^yGV+Y)Fe}4!@baH}Bu?{q{Q<`IY(yJy{0aB@TH^0<uK{s>p%c_pQ;~>VVZ"
    "9u{ycc18Zr->bA#fWjR`b78Ne%6%^zPAUdG%)~UJOsTWq6ha!?nYZWXR6Ps)io-VCRmB{euW5l$GHbfwp%tRE#Olg+cOqeicGLI8"
    "1iv)`kWkeoOZ|r+rpYuqx6zAP>&RcPiX}nKz{w5Q8;3;z+#FF!Ua)Ldc%~&HBWNg%e!s=-"
    "lN4B1{4NjK>4r6_QE%Mb{KK6VwUbxN;?G{7d0(^I2?7-b7O$vlo*1T=9PS;ASq~>*Jp2kw>=Ss$bS{C7uj0fk*NQA+8SyN~YT-"
    "Zd(qr+w>;f_o(g9$<~hyi(+wJzNY-MQG^UATOpyCfaDcH9nm52EPMgJN-"
    "{<8%mjiWhCNPaCkelFfi{q&bYj6v(Wms+I62G@gj`H4NlgrJLPyOIa&kDKiDZ-"
    "3sSY3u`&I9{gvFZJG(B@Cv}jjlWY+FKU#L{#k(2P4dmJ?vy|IvwK%R`!|oT-"
    "`@7V_;dYrTmq<#8Pv8JL%=xW7iGHDK@%uB&TG_6V_uy1e!rP&0hq#~a8GgJPkuX2Y5pex=ohM9-"
    "24B;KK)FKwhnFjD1IC1SPWLY@=v|D(>sAq@`Vc~Gz*lK!n_g&WpH!|w1bHygUt1YL1s+_A@4FDX|{lgQ3<aOC5)~HEUmIsD8H}z>"
    "M;0x!ZUxd|54pDbH#^I1Nh-mN_&n&D|^>^1dg8X(fPfXJpxB>674I$(4MFI15O+nX8"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
