# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-"
    "oa#U1%It6ux(6_J5o0X17VJX?xo=HLGQ7wL!FHt1+fVC5kCZ3zAG`?q(;>&V+kso1|=D!GfC_=&IO6q}a!Zh<)&(FM?IU7ax))HS"
    "18JAcDT7KSG-"
    ")&z;Stzfl}^?>%$w&pGGb?>lFHM|V9^t;09=Ks$|eq+=81@iB~rESXYXJ|=_g*X5JSF+~sP3iQ5lUn=;QSeU|YM71p2Q60m!IJ_!"
    "vs7_9k?y}*BzbtH=!3ez{m_`n+4;9gutMY{8$ZJ|$*ADy81J9SM{TSvFc!nqB5GqQ;f%Rv0q0@>c<&Y-"
    "5(*l;1qB0zOaQ1Ly{T)7%rnV`tenL4F(Ea5=7VFZ<=!8!~MPE^_d&{Mw+=p~|!e7&WhIFOqht_visn21_BAn%k4dBPW&B9a3dq?`"
    "fI`%vmMXkt*);)9@)})PVQe$1pD!UNdfRVH5{)kQmj-sjTC>oQGqEVa*sGVT?P3jbwMO5M#j!B7=Qyrq)loPmMqS>Zt=#-"
    "2aPL8P7IH6+(cMNNYWDS^1#~f;L06{t&Ch&CGqn2r_I-%B(VZk0+&bGPOl)?f_HSeq-YSy8QWNnrQgPfXF6KL8)xDBhQ_AVIl_Ov"
    "Z?oD2+j-"
    "lg*+`v(SyQFD%3c3~)&CgeyCG&yRHz=jT^s>2CAPT8GhkHaF*VU^eR)U?8gL3Id82Nz7!9_2MB)x2REDkE<jmM)Z<Ju(iBb(~tlz"
    "31v%lJ<S6fq}HQn;TG>mNSmq8omog3j7m-"
    "0lgr6g5Sr}fc#;+KHg5@J8URpKpQ?8oRqrO#_KrgLn*2E9#euaPYY8=JX5bCjD)dwwgcdB5l>3*wtLh`VxZZ>T$q#qaOkX5H*p3}"
    "Lo%4!p`da6l?+gkR&cr(h#uyS${a4>kdj>~{iLf{YM#1&I7FT5Tm(Q!X{DJnZLelCx>p=~Kg@yaOplDOgbof-"
    "i;j)3%!wDEcly=is$r^wFey)UL+$4d&8H8Vwx*gqlQwvN{jTmP*S2UD{M!%Btv}JN61tA$MEL5)<g$!5#4FvCy_cc~X7tbPPwn$f"
    "=YtpUthuo5z(VxEH5umJ=Hi0hYioz#+@Pj%Dnf8&069b!(f}ETt^!1Xwa5+DabJt@`4STpbR&29cOw1&;t}lRPe60KgsSmJmg24R"
    "@z#ZSTiJgl)_B7UWiz?ygC1TshL@2X0tueK#3ijrq<saaQVJ8icV+G{*UvmEyUL(#o2dvB0kSP(*aySLh#N2<9^GI}WD+J)ha2yP"
    "`{}ivZo6RVFEM5_w-"
    "H`n=rR}((q`i|UF;3Y@&*^gttkSp_tgZMQzsQ%1pspu5w9E4>&w9zI9gX3fdavj!eT%JQ{V?nhyw_EfbpK^YiGJ;-"
    "D6~_)xyFri#so&n;TJlQ{}CXqotlJk%qGK!Lz3iO&(f^v|Ng$&V@={%aZKdQtikrb#%{nbT4$g{7a%|_DH2`y63~5rR47U<nGJK_"
    "DhMLa`5k<&lkSdfTGP6XED-JjU~#Fs|~Tz;a|g>W|A}hnZa|-=R&jbxuz!;!+Wa1SY_X2v>do5qe#<z<CnvGt~NB5-"
    ">N)S8LAweQRgCLP9e9ix1!`L_|}!^*2V4nzB%;c;kn3b*Aez@xsqu5xZ_lCSq6E9?-WFD?A(dI-O;&KxwuUR@%ybl(e7-"
    "0F)05Kz|h{q{y@Fd{_K_WhZb7M0>kq9sRxP}?h|EI3W*HykOB-"
    "^|ASh{8d6c@4jIOS4;w%0Tk}CK%Kza56w;!kW3Nz3Q!k~I6P@+y1iv~W2sZ{zQGx`fNP!D+U_hiH(r%^FfF8*9Rv|w~nMgXUNq}9"
    "X3bt8%y!bp`xPFh(+zp9bCK427yF5KFWV6N?5bH4ytvcm^Wu3K)4FuP`ydm&fgKOeGxOza}3nOh}t_2O?)Q@6`%Ki_AONXnG#?zU"
    "}%wpuxYOJZ;P!$-fh8wEMN0*Xq^U1c^=C516Xqjy|KX{?}Lg>5rchCHkxtN*jd~<Gh-"
    "$L?8IaG~pUW#p>k8NL!?WiVN=AtcYXj~4VNQ{ZR(wp+LR*@wjUo%o9;`7W4&r1jFk-D@RC3|vBD}qb;-"
    "Ee<@wg4wj`}>*for8$WGzM!)MG(;o@(bkI^NwOAcrb741(Rl&$jRc`xfldwWBeQ1`3Ks3!{35;+{{GqCU4n4gJqvp"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
