# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-pO4T})fo9lu}x;@a2{o9_^pP{1UHqy&;JO$aHZ$(E8(l2oDUyo=9;Tw?n=_g)9=Iw`FxHPxb(s-4PIs<ExonA%C1`qIaAskA-X"
    "F_qmLI(6z^`bJA0s_bR|bFZ&$Y?Erz5S(-QpZ_`c|8;)nckVYt$&W?v$gO`u`yPP^M23hkIYpBAnF>);l-"
    "AQzwAM3IjMkf`Oj>WAGDA;?EMe=E73MHgHe{NrL1tt@R%Amph(-1l^Aroc1JxoYa;-"
    "2^c2tMz(JtiH{&S!wkmq$~sup#i2I!q=FKUF|g*wrbsOfdnR2}L<%^<0VkrwE8p>EU)y&LtQHt0Rbhjv5X05f_~JIrWA`_LYcG{J"
    "}$`sO(0+y5<g)kmr<7m0`prwC$19*6&#^PF-"
    "e;X&ejBqVak9~8sU5U=ok;pjl3DH;OJNG$9R@*#d&(xz!6^|M^?3g?&j>pU0oAMBgwu9wN4sv;YxB0E$?HmJ#(x5<Y5oD}3DJRb6"
    "yza_z)Zz<f+xM6T(!i^c4L`&IJ@FUJkoVINFSb~$T3XxfDtgUQpI>ZI9PRBwa?X66L)ot*Hxmi9@mtWN%l>|8qu?Z#|`NjOf_%ts"
    "iY76uI5mAs5P5ScuwU`jy=8)m5F;Z%8*-)vut=osTSsN@ZbsQNQm-=lIm-"
    ";MmgHT9gP@#+`L?Y@VT7Q<t6;q|goSCTj`6$2AoUO{3F|Vd_>;{=6<{XvsB$*_u>CaHcn@GY&RG(X7bM60RpKE8oNJ8-"
    "xR&6LmqPdFYg*iq)N$e$*dSkqkkZ6*)Ox*U(6AScZVxIKT<EnW^5)*vnl+U4BW_j3~ilowVT$XTAt2O)rAB-v7bck0i5-"
    "*FP>%3}?auOd=R5QPz@DZe11A!SK#0LVZMIVt>%el!hNfITM2??^IGDrw2suf-pzRJgCAElZkQ3O3_as7ZM!MXN&AGOO;us<kDd_"
    "UlYFe3!D%^#4(SOoP&<EmNLmfAplFZ{{Bfo74&HMJ~`ZCGk=%S)%1`E^U@MoasO{JWdKy_sq0%eD-qTZS?%N3t!$>6YPJ&Yacpmi"
    "<lplDPUxw)<GR`&i0zeBC;{Nzo=pe(c=~D?RW0BJ0_g_Uy}e{8`Un+B3Lr9eQXc?5=m2_Z)9KmidgUGs8ZaVxIirp^32X`ko+7jx"
    "VkDO&a<~GLHXedxuUQCjNHV_6$wmqey5gHi!jpkQwbPC~gj;Kt_p|I<=A|5t(425a?pke@$S?4Jt{^nRYHQnY`VRq=FO)MZpkp!b"
    "d^sIa%fv*+*+()DvzIWG$IKS~Wp3Aw>+1v}yyeKmy_vUZ%Aad8JmY&jz$b0#N{R31^}ozwBu(8yl{McdXwNv}yM(Cg*NiKJxat57"
    "FA#YAEe~>Xt3Xy0dIsnr-`nZO`p$yKisXw1DcS6(YNZP2LtF+Q1NRS%`}0P^@|%Iqsu0Yt-"
    "7wa~H=)1E<cM9UC8cZtTy5)QNr7Z1?1kn?hyjUi84&VeExN_kwMB_hyFeN-"
    "<s9+#pqAR*hj+s?01z7ITECA}}P01yY7AAhNJosqOs@N-"
    "4lxHPBGlB2?wqq6;A7*tr6Vkd&mFOW#K;bp=bAByGqcjHYo38!lllRRUmPX2EAu=`gndjSx|30Z^dz*^y^Xj|3(!Ts}J%*dFakl?"
    "F(Gd4MS<XoRTh$!l-d({klwRI|iMf)ZDqTto=xx4aSu?5T-}QkV+~2_E1E*Jp$a^D?7XV!jkz+Idu($s-"
    "^>iZl75p2<4*(!>hAJhCFM4*lWi+C*kgf2Qd`rtaY4&o-RBS!Z9`*|%Y3Z=Jhue_~n6SUa-Tp0u?mW9{9r?p~ftTYXz5+GSom{Sb"
    "<@aVfTZCBt^7m~Oo;$daI&jk<VEuZzOK9R0Xsqp~{YEIVh^(80JM*%e!{-"
    "jZZ7iwI|u9+!G?Cimeun~a=|O<X*4z9JU~u;M}7JcS!AHIy`npS5kFL$n_A20i8)2PlpFQ4O>}`6qhhjp%+X-"
    "x<C?aQg0arvFT~|6IENT&8~_<9vSc^q2bvZXYd#^w_6vX!N+2y3QDJ?Wo*uMIb0vFg32boJWJk^JhmcoEg9PT$$5SH}<ZG47&{KS"
    "?beq7&(J|av8X=6kBf}%&<c#W~j0RtcIx)RaOF2Wl9lw6=Exqam*~3%JIjQ0iv$<;MCdx2oMosa5>DeRm#j!$rM1dw#v$s!9C&t3"
    "B@4Kxp%hWeFB-3#)4+kk7%|QG}|7h`GFbWu)Uz`trD4zDzeThe2=c?|6F&KT)-"
    "8o0FDerBxz(#GGMhWNr6T98U}IxD4!)n8=12anr;o&LhJ|hc0E!bwQFlo<zsQo)Cw%H$k}EngSEv8gSG8_>`Dc0=NMP1h>~D19mg"
    "d|sPzkCm<tMu7%=Wx0hJ6qB0Dr}NSMVaAMti18aup7Jj#2+QGWKifOydhz{|<rgb7~^p!3dif|4)?L!!)keQuQ!fhAx-"
    "R?Tv3W=2?0twB!aXT%VI^}G<#_K<2j53?unqXsUjeX?`|dNk4Vv4|psd7V0%;p~VCFcJ11&mp*Ws5TG<z$7?!7_6vTa2trosyT>l"
    "h92IBLLt=zeK@SvhJ(T+aMVdSd?K?iU=9mT1bM(fM%&b<@q100gDN9qHfz2X6BQoGru^ZON4nYo_C7E#C|3fos5Aw_=P(-"
    "dlNuUWY;VlJI=|HU+ABG0ZO+2J@$#!LXDzL1OKZlmd$r-drF)Yy+3FtHTferuv-bA19hm9rq4(o!J=xyjbno!G{luo3usL(J-"
    "Vf{l)cpJAKenzq)+RoVXZug4`%h;2M^k-ccPBnq{+|3SdGBWG)TNaD1z@{u-"
    "CM`rJeFnK(`<W|^`}|?;^>CMwdDTQ<*cJU?Py<?S5Iaf-HWHbw6M2kmM$%wPPGl(8M|{hWk34qg}VpuqKxI||G0MFavm(l<hKvV>"
    "#f+*#ieJL2UCtGRu8S!t&Of*5B>|p*O&OE7gCPh%gXA+8uNwK|HH#ZqONJBE#>S2;%lqR*<E-U6FmOsy9UDMsGRah-VK5K#5Y<;+"
    "#7I?b`hV~IY;-"
    ">pLdYB?Q)F{(c6%;aDV)z2Kq^2k&Kfis8j_{6{fh?XW(A>F>Tx|ABUu{4=Eore(D0SU$eqVn7lC1L0KV=4~r2WBjKE@<_lU$YDIv"
    "V4G?7?DP7WdHZB{38*3%Q$?-@~;_^qC+^gSIEbL-"
    "3=X7r{jx6I&Gwzk~JDqnL@4DBSQ(5M0nmN19jOSSAV~)U{awbggL=Z3|P8@xnk4hqn1$i$Y@`gFMsS8N-"
    "A|8I_Ab81nWg+674vE)dJSTZWoEPXFFU@d?J~%(I{TekcKPx?&ljT%e!Zy!gf9o`V|IIe6H}20g_GQ@q6w_bHqzjB`|Bh}Yi6XBl"
    "buBgm58J%sXZWBZVt;~?7!eX2I2sfq*eCpT1rR{E_eli%jwNtsO>hMtkLY~i5Plvk=R1v>vpVU~ztiO1<zZCB+Mc4j-"
    "D~DM&P?Np3_FryMk*OXp{{!$<8tMl9vsH^t5L`gMnbrhA+Ia~LFT*=f~dfGId70doOhOk7=-"
    "WrMG=A+!@U|y<D`&S@b#$nSx$Geq;MNbyey%1(k!+O>+UK#>0c8wjmI<WaEclJzZI*N(Ggrz+`YeYI7#_WfQ7sT#SkCV|I3$NS@}"
    "*V1uu_RsoFi7iv^lj@`W+)s{mT@vij}KKnb({6yw)c@=<VM;gy&aNz~xa953RpnJ)oGcnb^~?|?@vmV1-"
    "laWTS!O;{#f)gzBH?=$Pg)@M{)ajLGy>>#~l+}bs%%4qB7#aD~sX;BOruMPjm`@&V<r%7AXnm}MC2JZ5KfP~X0P2dL8d<m0C4H~6"
    "$+E)a8wuXdh-MTK^9K+23ZtxcZ>8H49Gwv5UupBW;QqLF$S3QBaq_iETRiKudvV1<WJ{^YLAL5ToQ4Po;ak#KHX_6$rB09by91jT"
    "F1ES^u;d(%@UlC1k*4FzLYjZ7!Qbgm|me$<1-"
    ";VDbmS!qNcsA<^cYm&VFy}d#YdG|s&9n!kt(&!kyD!&#DCaqlYZx%3TP_>fwbf)IU0W`a?0#r9lRaDY6nT8Bh9nPfS$C0rTl*Opt"
    ")<8V4{Ip$B)J9c2@*f|Y0mr?pQm+J"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
