# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-n1L-"
    ")kI29G}_UyGw41ITKAZv^XiE9^yr5s}HS0G$&lsTuO5OI)u$+XDSmnGwXL}qlqa!!3Xt4`sAxVmcA$oA_x`w4_rvWIQSqGLEj3kF"
    "MV=mlMAVFU}wKO^Z9<~`~7@Bv$xTq;qSfh-"
    "P3md3Nh403^OmmYhKsG&h`_(>$9L6unHSurB6%UlC_3e*;?fdzh2Gft?L_FB!W@KGm=uE1h|kQ78FRV0C=qF8kd@rTv9^QM8q@}H"
    "@}zU;zmnmnkEScq9lLrl1O;tZ<kUXn~+MWG}S`MtZg2BdtrX&wN_^#T5K+LW)?fqTQjXrjQ>-"
    "O@2YvXs74>`ZJ|%REhI;@H&|H>(2;R{AAcD$yk%K9XKiQc@&Mshw(t_F`}tqid_Cu|X$wk-%=x+^DX5rdicrEo(m*+6oN!69-"
    "0h@-l9)ouH6@y_r3z@$s8)#`OF|NEX&@_9GH&TROiP+`#x0?_qj=LY$`itb<5YoAWO+H7Z?=|~3FAo-"
    "Y>>nUIVbM?OyB&5#2moJR%C;u9PAm^Z-r(&O2i6K*l28u)Wygx%C^ZKQS?tWijW4sU`||or`5K+U%1d*bRB4RqGtQe*5X2YzS-"
    "{70~0V2YvZZRRJdFhprolC?v#UH^GrEYImFzA`yi)_%(aD(`(qiz(^fEi8XO&<8|j95JWe>3(f&$w$PH@NEwoQ|#!fwS?-"
    "&}J_<FoQb?WN+&!aacf12DGo$bx-o_eu2*RM@)2hacU<kP*mTQ#yBOzno_{b2mA>*@m<Di1XDMWLYs<s1N3y`##xjCJWiYk0MC6r"
    "qO(7Q@%Q2lciZ{*M+1Xz%@J5ORuZ8w4)7dKrf83#xW9ex||r?{N(-hAG)kk-"
    "{;@$sVUL;?~Cp?0rauwp3beWSTRWu$zxL@Jj`OyT?!Vk2kJ9^~0+_p8xKAZ|?W-q0c`4^2+B|Zap#m?dZ<P>7DS*ui@G4@a#_b@-"
    "JiC;cP#cg@=pV+OFH)0@pc6aJAMwaFI>0qEu3^m`W5e6-SY&M$x6*!gv&cyRduJxb%yD7CBu*Mbsks`$Ol}6w4F-"
    "3Y>7iDwpn*o$mM;<KNKIpXlUmG<>Iw9(lHpYWK=jJn_$@hnu(v@h_B6LJ|"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
