# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.
from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
    "c-oCr&rcgi7@gT&8=JMU4M|MWv`h@GSfEDzp|k>&wu)2r5YZ^+L>-~EXE5uocdglVh%H-"
    "1Z4X9@gr!O?M|w+z@>lQ=#G#d~Nff2(iJRNx#HF3Fjj;rZI?{eK`+e_w`{wP={sjhx)Scj~t33V!Fu>3RtKAu{LM&tHN4P4Lpr#x"
    "N;BrP9==ShS7TqtP=&k?<mY@qy%DF*oZ(ykc_Ivp%s6e`r1y!C)fO~g%Mjq%^&URPi{a(GQRFvG%IsAPD9j!<?|C=}<c(_<muyP+"
    "z`0(@pfxfG7Uvla>D5<XtU{BTK2K&1hIS1{*kh>tCbi5gjy?E#por|1B?1R3aAUAdngYQ(Gd$F$qoMf^8+XVN^R{?k!t5*OHlzVI"
    "spd&$mgGr!`6k{AdjQB|Emf;#@9l7LzYomfrbyRe8YT5`Bv~JV9jvSIL@^r?|+sLx>X-Y&*r<o1oz8&w-bix-"
    "j>nwCuVhBPs?YLB1K)1{uzfFy-Vd*BCb`KuAMbn-"
    ";%c#Zs92t}7)*8v%Im1EIY1=kAS<*nnK`XRK<`6NBJm*6_NC`OykMn8Uv>lYC2fwZx8QVFf>n!dPw@9r4p<LpCLQYsPdb?tP$;)5"
    "f)D#A9Gq}v)9R^o5iAhPDNjI(X$Tz9f{6cCb^;vA`M&({vPC2v35S67kI{I0hu%n-"
    "NEX(nDygZyVEVN>XJ!>jcix!uL3D#Ym`7L3yX_N``WptNhZCYZ(j;mAG*)-e@=G6-"
    "YVqvD_Y{Oy_B}{gTY3AX|jRN!1?kt<c(!5L&`(S}V>sYXJNAOx^L#GZ?#6-"
    "o{$3pxSrwxpW)vY;Rp6&W_e957i`HW4;yr5hwx`ye*3nezz<z6@V1NA&v6IF_MpE%{tzdUS#zb}D6xD|@L_JTmPsiKC8_AWkB4%P"
    "R!5`PYjwJ(6nZ`FdW3*-L))jwNHJdehj(b-"
    "0H_EF+6`a$ihwikrQo1s`E6nirH$?u_0Tj95x;i*P=YH#I_@XX7|<=s>xqP4=~92t3Mpwy0X!uAyq9^Kj8-mF&-"
    "L+{p<whu(7x4wR^26wJ+U$4*aeYocys&iWjp>L#<dvAAgm*=LM>P$nO=@dD2AiT4<y;$dks~xaUt$qAMss7RT-"
    "?c(x^+Y{cEAQTFgs#<;mul##I#FMGqD;IJCsBhdnoPwJr6Cc7LB9cdO{^z)IQA{&ZCo_T4LaHRC2{Y<JhWv9;WOZW21Z{i3lMcW{"
    "sRT-YDo"
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
