from __future__ import annotations

import argparse
import base64
import marshal
import textwrap
import zlib
from pathlib import Path


DEFAULT_PATHS = ("main.py", "launcher.py", "src")
HEADER = "# Generated by scripts/obfuscate_python_tree.py. Do not edit by hand.\n"


def iter_python_files(root: Path, entries: list[str]):
    for entry in entries:
        path = root / entry
        if path.is_file() and path.suffix == ".py":
            yield path
        elif path.is_dir():
            yield from sorted(path.rglob("*.py"))


def obfuscate_file(root: Path, path: Path) -> bool:
    relative = path.relative_to(root).as_posix()
    source = path.read_text(encoding="utf-8-sig")
    if source.startswith(HEADER):
        return False

    code = compile(source, relative, "exec")
    payload = base64.b85encode(zlib.compress(marshal.dumps(code), level=9)).decode("ascii")
    wrapped = "\n".join(f'    "{chunk}"' for chunk in textwrap.wrap(payload, 100))
    loader = f"""{HEADER}from __future__ import annotations

import base64 as _base64
import marshal as _marshal
import zlib as _zlib

_PAYLOAD = (
{wrapped}
)

exec(_marshal.loads(_zlib.decompress(_base64.b85decode(_PAYLOAD))), globals(), globals())
"""
    path.write_text(loader, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Obfuscate Xomacito Python sources in-place.")
    parser.add_argument("--root", default=".", help="Repository root. Defaults to the current directory.")
    parser.add_argument(
        "paths",
        nargs="*",
        default=list(DEFAULT_PATHS),
        help="Files or directories to obfuscate. Defaults to main.py, launcher.py and src.",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    changed = 0
    for path in iter_python_files(root, args.paths):
        changed += int(obfuscate_file(root, path))
    print(f"Obfuscated {changed} Python files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
