; Retired runtime components only: never touch user media, models or settings.
Type: filesandordirs; Name: "{app}\_internal\rembg"
Type: filesandordirs; Name: "{app}\_internal\rembg-2.0.76.dist-info"
Type: filesandordirs; Name: "{app}\_internal\pymatting"
Type: filesandordirs; Name: "{app}\_internal\numba"
Type: filesandordirs; Name: "{app}\_internal\llvmlite"
Type: filesandordirs; Name: "{app}\_internal\llvmlite.libs"
Type: filesandordirs; Name: "{app}\_internal\scipy"
Type: filesandordirs; Name: "{app}\_internal\scipy.libs"
Type: filesandordirs; Name: "{app}\_internal\skimage"
Type: filesandordirs; Name: "{app}\_internal\PySide6\qml\QtWebEngine"
Type: filesandordirs; Name: "{app}\_internal\PySide6\qml\QtWebView"
Type: files; Name: "{app}\_internal\PySide6\Qt6WebEngineCore.dll"
Type: files; Name: "{app}\_internal\PySide6\Qt6WebEngineQuick.dll"
Type: files; Name: "{app}\_internal\PySide6\Qt6WebEngineQuickDelegatesQml.dll"
Type: files; Name: "{app}\_internal\PySide6\Qt6WebView.dll"
Type: files; Name: "{app}\_internal\PySide6\Qt6WebViewQuick.dll"
